version: '2'

services:
  recipientVerification:
    container_name: recipientVerification
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./.env:/opt/.env
    ports:
    - 8080:8080