version: '2'

services:
  recipient_verification:
    container_name: recipient_verification
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./.env:/opt/.env
    ports:
    - 8080:8080